### ISSUE TITLE
Getting Wrong Results

### ISSUE THREAD

**Issue by m-pektas** [tae898/age-gender#1]
Hi @tae898 ,  Firstly, Thanks for your clear code.  I need only your age gender model inference into my code. Therefore, I used the original insightface pytorch arcface  repository  and r100 model to obtain embeddings. Then, I fed this embedding into your age gender model. But I get wrong results. For example, I tried almost 20 images and all gender results are 1. What do you think about that? How can I solve this?

**Comment by tae898** [comment]
Hi, thanks for your interest in my repo. My age and gender models are also trained on the embeddings from `arcface_r100_v1`, so it should work. hmm ...

**Comment by tae898** [comment]
Can you perhaps send me the images that you want to run inference on? You can send them to me at tae898@gmail.com

**Comment by m-pektas** [comment]
> Can you perhaps send me the images that you want to run inference on? You can send them to me at [tae898@gmail.com](mailto:tae898@gmail.com)

I sent you an e-mail.

**Comment by tae898** [comment]
@m-pektas 

Check out [this demo video](https://youtu.be/Dna_Hp-s78I). It might help you

**Comment by m-pektas** [comment]
> @m-pektas
> 
> Check out [this demo video](https://youtu.be/Dna_Hp-s78I). It might help you

Thanks for video link @tae898 . When I use  r100_v1 model that you used, rather than insigtface pytorch r100 for embedding, I got correct results.

**Comment by maria-zafar** [comment]
Hello can you please guideline if I want to run on colab?

**Comment by tae898** [comment]
> Hello can you please guideline if I want to run on colab?

@maria-zafar 
I created a new issue:
https://github.com/tae898/age-gender/issues/2

I'll address it there.

**Comment by maria-zafar** [comment]
> > Hello can you please guideline if I want to run on colab?
> 
> @maria-zafar
> I created a new issue:
> #2
> 
> I'll address it there.

I am looking for the guidelines to run your code in colab but getting errors so shall be grateful if you address ASAP. If you want me to state you details about how I am doing we can discuss over an email?

**Comment by tae898** [comment]
@maria-zafar 
I prefer addressing it here in the issue tab.
Can you write your error mesages, etc. at https://github.com/tae898/age-gender/issues/2?
