### ISSUE TITLE
What I should download from the Adience?

### ISSUE THREAD

**Issue by vegetableclean** [tae898/age-gender#10]
Hello, I am a newer one here, sorry for the easy question, I am wondering what kind of data I should download from this https://talhassner.github.io/home/projects/Adience/Adience-data.html since they have both image and label files on the website.
And after downloading, what format I should place at ./data/Adience/. Can you be more specific about this? Thanks a lot!

**Comment by tae898** [comment]
I updated the README. Can you give it a try?

**Comment by vegetableclean** [comment]
Sure Thanks a lot! I would try it again!

**Comment by tae898** [comment]
My dataloader only loads the embeddings. If you want to use a CNN for the entire face / image, you'll have to either modify the dataloader or make one for yourself.

The only thing the docker does is to extract the embeddings.
