### ISSUE TITLE
The method is not allowed for the requested URL.

### ISSUE THREAD

**Issue by herokarimpoor** [tae898/age-gender#12]
hi
Thanks for sharing the information

I get this error when I run the file app.py

method in @app.route("/", methods=['POST']) is post but when i request is get?
please help me
![Uploading Screenshot from 2022-09-12 16-34-51.png…]()

![Screenshot from 2022-09-12 16-34-51](https://user-images.githubusercontent.com/52469283/189648870-0fdc0dd5-1296-41f7-93d3-5190688e1ef0.png)

**Comment by tae898** [comment]
Hey,

You are supposed to run something like

```sh
python client.py --mode image --image-path test-images/gettyimages-1067881118-2048x2048.jpg
```
or
```sh
python client.py --mode webcam
```

You can learn more [in this section](https://github.com/tae898/age-gender#deployment).

**Comment by herokarimpoor** [comment]
ok Solved
thank for you
