### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by herokarimpoor** [tae898/age-gender#13]
when i run :
python3 client.py --mode image --image-path test-images/gettyimages-1067881118-2048x2048.jpg

i have this eror:

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe1b90cac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
![Screenshot from 2022-09-14 14-25-29](https://user-images.githubusercontent.com/52469283/190123432-6579e913-4c3a-43c2-ab79-c8ab6e35e43b.png)

**Comment by tae898** [comment]
Make sure that your client is making correct API calls to the flask app URLs.

[See the code](https://github.com/tae898/age-gender/blob/b5aa3c88b97fc141e222836a35a3eb89e6258dec/client.py#L237).

**Comment by herokarimpoor** [comment]
ok sloved
thank

**Comment by herokarimpoor** [comment]
Hi
I want to use your codes for my program, but I have this problem in my program

ModuleNotFoundError: No module named 'parse_config'


Where should I put parse_config this file to solve my problem?
thank you

**Comment by tae898** [comment]
Hey,

Can you copy the full error here?

**Comment by herokarimpoor** [comment]
I have attached my file
The problem occurs when it is loaded

checkpoint = torch.load(checkpoint, map_location=torch.device(self.device))

and i get this error:
ModuleNotFoundError: No module named 'parse_config'

**Comment by tae898** [comment]
hmm I don't get the same error.
Can you run `git pull` and go through [README.md](https://github.com/tae898/age-gender/blob/main/README.md) again? Perhaps you didn't install the `requirements.txt`?

**Comment by herokarimpoor** [comment]
I solved the problem.
thank for you
How did you detect the face and in which part of the codes is it located?
how model for face detector and out embedding?

**Comment by tae898** [comment]
> How did you detect the face and in which part of the codes is it located? how model for face detector and out embedding?

The face detection (bounding box) and the embedding extraction (512 dimensional feature vector extraction) are done in [this repo](https://github.com/tae898/face-detection-recognition
).
