### ISSUE TITLE
What is model for arcface?

### ISSUE THREAD

**Issue by kevinzezel** [tae898/age-gender#15]
Hi,

First of all congratulations for the work.

What is model for arcface?
 
R100 | Casia 
R100 | MS1MV2
R18 | MS1MV3 
R34 | MS1MV3
R50 | MS1MV3
R100 | MS1MV3
R18 | Glint360K
R34 | Glint360K
R50 | Glint360K
R100 | Glint360K 

Regards,
Kevin

**Comment by tae898** [comment]
I used `arcface r100 v1`.  Not exactly sure which one it is in your list, though.
