### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by falimoradi** [tae898/age-gender#4]
Hi
when I try to run your .ipynb file in colab, I get ConnectionRefusedError.
How can I fix it?

**Comment by tae898** [comment]
Hey,

I just tested and it works fine to me though.
Did you restart the runtime before the cell where you visualize images?

![image](https://user-images.githubusercontent.com/10544311/142764931-3caaf725-e183-43ac-a46f-76acf59edd79.png)

If you still run into a problem, please write your error messages here.

Tae
