### ISSUE TITLE
onnx export

### ISSUE THREAD

**Issue by MyraBaba** [tae898/age-gender#7]
Hi,

Do you have onnx export ?

**Comment by tae898** [comment]
Hey,

Only pytorch is supported at this moment.

**Comment by MyraBaba** [comment]
@tae898 

face detection looks mxnet right ? arcface100

**Comment by tae898** [comment]
> @tae898
> 
> face detection looks mxnet right ? arcface100

The face detection (bounding boxes and landmarks) uses `retinaface_r50_v1`,
and the face recognition (extracting 512 dimensional face embedding vectors) uses `arcface_r100_v1`
